/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtentiRouteImport } from './routes/utenti'
import { Route as UploadMultiploRouteImport } from './routes/upload-multiplo'
import { Route as TalentPoolRouteImport } from './routes/talent-pool'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PosizioniRouteImport } from './routes/posizioni'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as CandidatiRouteImport } from './routes/candidati'
import { Route as AnalisiPeriodoRouteImport } from './routes/analisi-periodo'
import { Route as AnalisiRouteImport } from './routes/analisi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatiIdRouteImport } from './routes/candidati.$id'

const UtentiRoute = UtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadMultiploRoute = UploadMultiploRouteImport.update({
  id: '/upload-multiplo',
  path: '/upload-multiplo',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentPoolRoute = TalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PosizioniRoute = PosizioniRouteImport.update({
  id: '/posizioni',
  path: '/posizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatiRoute = CandidatiRouteImport.update({
  id: '/candidati',
  path: '/candidati',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisiPeriodoRoute = AnalisiPeriodoRouteImport.update({
  id: '/analisi-periodo',
  path: '/analisi-periodo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisiRoute = AnalisiRouteImport.update({
  id: '/analisi',
  path: '/analisi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatiIdRoute = CandidatiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidatiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisi': typeof AnalisiRoute
  '/analisi-periodo': typeof AnalisiPeriodoRoute
  '/candidati': typeof CandidatiRouteWithChildren
  '/impostazioni': typeof ImpostazioniRoute
  '/posizioni': typeof PosizioniRoute
  '/ranking': typeof RankingRoute
  '/talent-pool': typeof TalentPoolRoute
  '/upload-multiplo': typeof UploadMultiploRoute
  '/utenti': typeof UtentiRoute
  '/candidati/$id': typeof CandidatiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisi': typeof AnalisiRoute
  '/analisi-periodo': typeof AnalisiPeriodoRoute
  '/candidati': typeof CandidatiRouteWithChildren
  '/impostazioni': typeof ImpostazioniRoute
  '/posizioni': typeof PosizioniRoute
  '/ranking': typeof RankingRoute
  '/talent-pool': typeof TalentPoolRoute
  '/upload-multiplo': typeof UploadMultiploRoute
  '/utenti': typeof UtentiRoute
  '/candidati/$id': typeof CandidatiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisi': typeof AnalisiRoute
  '/analisi-periodo': typeof AnalisiPeriodoRoute
  '/candidati': typeof CandidatiRouteWithChildren
  '/impostazioni': typeof ImpostazioniRoute
  '/posizioni': typeof PosizioniRoute
  '/ranking': typeof RankingRoute
  '/talent-pool': typeof TalentPoolRoute
  '/upload-multiplo': typeof UploadMultiploRoute
  '/utenti': typeof UtentiRoute
  '/candidati/$id': typeof CandidatiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisi'
    | '/analisi-periodo'
    | '/candidati'
    | '/impostazioni'
    | '/posizioni'
    | '/ranking'
    | '/talent-pool'
    | '/upload-multiplo'
    | '/utenti'
    | '/candidati/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisi'
    | '/analisi-periodo'
    | '/candidati'
    | '/impostazioni'
    | '/posizioni'
    | '/ranking'
    | '/talent-pool'
    | '/upload-multiplo'
    | '/utenti'
    | '/candidati/$id'
  id:
    | '__root__'
    | '/'
    | '/analisi'
    | '/analisi-periodo'
    | '/candidati'
    | '/impostazioni'
    | '/posizioni'
    | '/ranking'
    | '/talent-pool'
    | '/upload-multiplo'
    | '/utenti'
    | '/candidati/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisiRoute: typeof AnalisiRoute
  AnalisiPeriodoRoute: typeof AnalisiPeriodoRoute
  CandidatiRoute: typeof CandidatiRouteWithChildren
  ImpostazioniRoute: typeof ImpostazioniRoute
  PosizioniRoute: typeof PosizioniRoute
  RankingRoute: typeof RankingRoute
  TalentPoolRoute: typeof TalentPoolRoute
  UploadMultiploRoute: typeof UploadMultiploRoute
  UtentiRoute: typeof UtentiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utenti': {
      id: '/utenti'
      path: '/utenti'
      fullPath: '/utenti'
      preLoaderRoute: typeof UtentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-multiplo': {
      id: '/upload-multiplo'
      path: '/upload-multiplo'
      fullPath: '/upload-multiplo'
      preLoaderRoute: typeof UploadMultiploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-pool': {
      id: '/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof TalentPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posizioni': {
      id: '/posizioni'
      path: '/posizioni'
      fullPath: '/posizioni'
      preLoaderRoute: typeof PosizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidati': {
      id: '/candidati'
      path: '/candidati'
      fullPath: '/candidati'
      preLoaderRoute: typeof CandidatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisi-periodo': {
      id: '/analisi-periodo'
      path: '/analisi-periodo'
      fullPath: '/analisi-periodo'
      preLoaderRoute: typeof AnalisiPeriodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisi': {
      id: '/analisi'
      path: '/analisi'
      fullPath: '/analisi'
      preLoaderRoute: typeof AnalisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidati/$id': {
      id: '/candidati/$id'
      path: '/$id'
      fullPath: '/candidati/$id'
      preLoaderRoute: typeof CandidatiIdRouteImport
      parentRoute: typeof CandidatiRoute
    }
  }
}

interface CandidatiRouteChildren {
  CandidatiIdRoute: typeof CandidatiIdRoute
}

const CandidatiRouteChildren: CandidatiRouteChildren = {
  CandidatiIdRoute: CandidatiIdRoute,
}

const CandidatiRouteWithChildren = CandidatiRoute._addFileChildren(
  CandidatiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisiRoute: AnalisiRoute,
  AnalisiPeriodoRoute: AnalisiPeriodoRoute,
  CandidatiRoute: CandidatiRouteWithChildren,
  ImpostazioniRoute: ImpostazioniRoute,
  PosizioniRoute: PosizioniRoute,
  RankingRoute: RankingRoute,
  TalentPoolRoute: TalentPoolRoute,
  UploadMultiploRoute: UploadMultiploRoute,
  UtentiRoute: UtentiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
